#!/bin/bash

run=0
failed=0

function check
{
  name=${1#src/}
  case "$1" in
    *.class)
      name=${name%.class}
      $JAVA -cp src "$name"
      ;;
    *.sh)
      bash "$1"
      ;;
  esac
  if [ "$?" != "0" ]; then
    echo "$name: FAILED"
    failed=$((failed + 1))
    [ "$SUITE_RUN_ALL" != "1" ] && exit 1
  else
    echo "$name: OK"
  fi
  run=$((run + 1))
}

for t in $(find src \( -name "*Test.class" -o -name "*test.sh" \) | sort -f); do
  check $t
done

echo ""
echo "Tests run: $run, Failed: $failed"
if [ "$failed" != "0" ]; then
  exit 1
fi
