#!/bin/bash

run=0
failed=0

function check
{
  class=$(echo $1 | sed "s/.class//g" | sed "s/^src.//g")
  output=$($JAVA -cp src $class)
  if [ "$?" != "0" ]; then
    echo "$class: FAILED"
    failed=$((failed + 1))
    [ "$SUITE_RUN_ALL" != "1" ] && exit 1
  else
    echo "$class: OK"
  fi
  run=$((run + 1))
}

for t in $(find src -name "*Test.class"); do
  check $t
done

echo ""
echo "Tests run: $run, Failed: $failed"
if [ "$failed" != "0" ]; then
  exit 1
fi
